### PR TITLE
Arrowhead-Class Long Range Scoutship

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
adds ship, one I had made a time ago, but now updated and improved, with Less Bugs:tm:
## Why It's Good For The Game
ship
arrowheadMK2

## Changelog
:cl:
add: Arrowhead-Class Long Range Scoutship
/:cl:

### CODE REVIEW

**Comment by retlaw34** [comment]
upstream? it was well liked there too

**Comment by TheNeoGamer42** [comment]
the fact the checks fail because of piping issues is actually nice today

**Comment by TheNeoGamer42** [comment]
> upstream? it was well liked there too

iunno maybe, im too lazy to setup my git for shiptest itself right now though so uh

**Comment by Vexylius** [comment]
sthdjyesfdwdfssadebfdhjd rtf tdfdsgsfduhdfs hhjdfs yhudsf ahs dobhjsafgd jhfg sdjk sfgdjk dfsghjo sfgdh aeswfewr ioqdcknoc

**Comment by TheNeoGamer42** [comment]
> sthdjyesfdwdfssadebfdhjd rtf tdfdsgsfduhdfs hhjdfs yhudsf ahs dobhjsafgd jhfg sdjk sfgdjk dfsghjo sfgdh aeswfewr ioqdcknoc

engrish please, what

**Comment by TheNeoGamer42** [comment]
anyone who objects to me merging Right Now this say "i am an idiot dumbhead" within 5 minutes and ping me

**Comment by Vexylius** [comment]
oh no

**Pull request merged**
