### PR TITLE
IT COMES (the human resprite!)

### PR DESCRIPTION
**Pull request by zestybastard**
## About The Pull Request

Resprites humans.

(note: two pixel eyes are not in yet due to the fact they get absorbed by the greyscale and i'm not sure how to implement them otherwise. this will change in the future)

## Why It's Good For The Game

Look at these guys.
image

## Changelog
:cl:
imageadd: new human sprites
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
They don't know that I am going to poke their eyes because I'm evil, clueless little humans

**Comment by zestybastard** [comment]
CHECKS PASSING :eyes:

**Comment by Vexylius** [comment]
naked femail is the same as naked mail, is this intended?

**Comment by zestybastard** [comment]
> naked femail is the same as naked mail, is this intended? (human_chest_f and human_chest_m)

we did like. None their binary which was a key point of this

**Comment by retlaw34** [comment]
i think this needs the white eyes before it can be tmed

**Comment by zestybastard** [comment]
> i think this needs the white eyes before it can be tmed

i dont know how to do eye overlay coding is the thing

**Comment by retlaw34** [comment]
what the fuck how did i end up here i thought this was the shiptest repo at 2am

**Comment by zestybastard** [comment]
gwa gwa

**Comment by Vexylius** [comment]
Ok, I'm going to merge this as we have no way of actually testmerging stuff at the moment. Will revert if bad :v

**Pull request merged**
